<a href="https://colab.research.google.com/github/MadhuraTonpe165/InClassLiveCodingBooks/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Installing numpy
!pip install numpy

In [5]:
# Importing numpy
import numpy as np


In [9]:
# Creating a numpy array
arr = np.array([1,2,3,4,5])
print('Array:\n', arr)
print('Shape :' , arr.shape)
print('Type :', type(arr))
print('Data Type :', arr.dtype)
print('Number of Dimentions :', arr.ndim)

Array:
 [1 2 3 4 5]
Shape : (5,)
Type : <class 'numpy.ndarray'>
Data Type : int64
Number of Dimentions : 1


In [ ]:
'''
ndarray - > n dimentional array
Numpy array are compared wuth Python Lists on 2 points - >
  1. size - > Numpy Data structures take up less space
  2. Performance - > they have a need for the speed and are faster than Lists
'''

In [11]:
#Size Comparisons
import sys

#Declarating a list of 1000 elements
S = range(1000)

#Output
print('Size of each element of list in byte : ', sys.getsizeof(S) )
print('Size of the whole List in bytes :', sys.getsizeof(S)* len(S))

#Declarating a numpy array of 1000 elements
D = np.arange(1000)

#Output
print('\nSize of each element of numpy array in byte : ', D.itemsize )
print('Size of the whole Numpy array in bytes : ', D.size * D.itemsize)



Size of each element of list in byte :  48
Size of the whole List in bytes : 48000

Size of each element of numpy array in byte :  8

Size of the whole Numpy array in bytes :  8000


In [12]:
#np.arange(start, end, step)

np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# ending value is not included

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Default starting value is 0
# Default step is 1

In [17]:
#np.arange(start, end, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [14]:
#np.arange(start, end, step)
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(stop = 10, step = 2)

array([0, 2, 4, 6, 8])

In [21]:
np.arange(start = 10, stop = 100, step = 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
#defining stop to a array is mandatory

In [23]:
# Performance Comparison
# Importing Time

import time

# Size of arrays and lists
size = 1000000

#Declaring lists
list1 = range(size)
list2 = range(size)

# Declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Captuirng the time before the operation
initialTime = time.time()

#Mutiplying the elements
resd = [(a * b) for a, b in zip(list1, list2)]

#Capturing the time after the operation
print('Time taken by Lists to perform multiplication :', (time.time() - initialTime)*1000, 'ms')


# Captuirng the time before the operation
initialTimearray = time.time()

#Multiplying the arrays
res = array1 * array2

# Capturing the time after the operation
print('\nTime taken by Numpy aray to perform multiplication :', (time.time() - initialTimearray)*1000, 'ms' )

Time taken by Lists to perform multiplication : 89.02311325073242 ms

Time taken by Numpy aray to perform multiplication : 12.235641479492188 ms


In [24]:
89.02311325073242/12.235641479492188

7.275720966484801

In [ ]:
#numpy array are faster than python lists

In [ ]:
#multiplying in 100 to convert to miliseconds oterwise it is in microseconds

In [25]:
# Numpy arrays are homogenous means it support only one data type
arr = np.array([1, 2.0, 'numpy'])
print('Array : ', arr)
print('Data Type :', arr.dtype)

Array :  ['1' '2.0' 'numpy']
Data Type : <U32


In [ ]:
#u32 -> unistring https://stackoverflow.com/questions/56944812/how-to-interpret-python-output-dtype-u32

In [26]:
arr = np.array([1, 2.0, 5.7])
print('Array : ', arr)
print('Data Type :', arr.dtype)

Array :  [1.  2.  5.7]
Data Type : float64


In [27]:
arr = np.array(['num', 2.0, 'numpy'])
print('Array : ', arr)
print('Data Type :', arr.dtype)

Array :  ['num' '2.0' 'numpy']
Data Type : <U32


In [29]:
arr = np.array([1, 2, 3.5])
print('Array : ', arr)
print('Data Type :', arr.dtype)

Array :  [1.  2.  3.5]
Data Type : float64


In [30]:
#random module Numpy - > used to create an array of random values in the range(0, 1), nither 0 nor 1
np.random.rand(3, 4)

array([[0.69069455, 0.45095696, 0.51909973, 0.87937068],
       [0.04029383, 0.27800555, 0.75322813, 0.23079993],
       [0.50543031, 0.98926075, 0.26317709, 0.85506079]])

In [31]:
#np.random.randn- > used to create an array of random nomal values
# with mean  = 0 and stadard deviation = 1
np.random.randn(2, 5)

array([[0.0250558 , 0.19725497, 0.71598274, 0.25745692, 0.90477079],
       [0.1293588 , 0.09039092, 0.19844685, 0.61000435, 0.16510761]])

In [32]:
# np.randon.randint(low, high, size)
np.random.randint(low = 1, high = 100, size = (3, 5))

array([[33,  9, 24, 70, 47],
       [97,  7, 11, 65, 40],
       [22, 67, 41, 56, 76]])

In [ ]:
# High valkue not included
# randn and rand will always will create float array